image: node:10.15.3

pages:
  stage: deploy
  before_script:
    - npm install
    - npm install -g truffle
    - echo "MNEMONICS=buffalo excite exchange cost salad indicate tenant boil meadow verify pretty head" >> .env
  script:
  - truffle build  
  - mkdir .public
  - cp -r jsdeployer .public/jsdeployer
  - mv build .public
  - rm -rf public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - feature/jsdeployer
